name: simper_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  # flutter_bloc: ^2.1.1
  cupertino_icons: ^0.1.2
  flutter_plugin_pdf_viewer: ^1.0.7
  provider: ^3.2.0
  flutter_datetime_picker: ^1.3.1
  connectivity: ^0.4.6+1
  http: ^0.12.0+3
  shared_preferences: ^0.5.6
  shimmer: ^1.0.1
  auto_size_text: ^2.1.0
  photo_view: ^0.9.1
  cached_network_image: ^2.0.0
  flutter_local_notifications: ^0.9.1+3
  flutter_app_badger: ^1.1.0
  badges: ^1.1.0
  firebase_messaging: ^6.0.9
  cloud_firestore:

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/simper.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSansBold.ttf
        - asset: assets/fonts/ProductSansItalic.ttf
        - asset: assets/fonts/ProductSansRegular.ttf
          weight: 400

    - family: Gilory
      fonts:
        - asset: assets/fonts/GilroyExtraBold.otf
        - asset: assets/fonts/GilroyLight.otf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold.otf
        - asset: assets/fonts/PoppinsRegular.otf
        - asset: assets/fonts/PoppinsSemiBold.otf
        - asset: assets/fonts/PoppinsMedium.otf
        - asset: assets/fonts/PoppinsItalic.otf
        - asset: assets/fonts/PoppinsLight.otf
          weight: 400

    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SanFrancisco-Regular.ttf
        - asset: assets/fonts/SanFrancisco-RegularItalic.ttf
